Toolbar and Headline of the Mobile Version Of My Portfolio
spydaspider/Dickson-Portfolio-Repo pull request #7
Opened 2022-05-26 13:26 UTC by spydaspider

**Toolbar and Headline of My Portfolio Mobile.**
Locate the index.html in the project folder and view the site.

2022-05-26 14:12 UTC, phelian23 requested changes
Hi @spydaspider, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Correct use of Github Flow
✅ Good commit messages
✅ Good README template

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 14:12 UTC, phelian23 commented on style.css
> +
- [ ] Kindly make sure that your design (Font family, margins, decorations) looks close as possible to that of the Figma design.
- [ ] Also Kindly remove the horizontal scroll on the mobile version

2022-05-26 14:41 UTC, spydaspider commented on style.css
> +
Thank you, Sir! I will attend to it at once.

2022-05-27 01:05 UTC, spydaspider commented on index.html
> +      </nav>
Hi Sir! Please I don't understand the second instruction.(Wrap the hamburger icon in the <nav> tag.

2022-05-27 06:42 UTC, phelian23 commented on index.html
> +      </nav>
@spydaspider, the menu icon (hamburger) should be wrapped in the `<nav>` tag

2022-05-27 08:46 UTC, spydaspider commented
Okay I get it now. Thank you.

On Fri, 27 May 2022, 6:42 am Oluwafemi Awoyemi, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/spydaspider/Dickson-Portfolio-Repo/pull/7#discussion_r883322633>
> :
>
> > +      <nav class="flex-div">
> +        <div class="toolbar-left">
> +          <a href="" class="logo"> My Logo </a>
> +        </div>
> +        <div class="toolbar-right">
> +          <a href=""><img src="images/menu-icon.png" alt = "image"/></a>
> +        </div>
> +      </nav>
>
> @spydaspider <https://github.com/spydaspider>, the menu icon (hamburger)
> should be wrapped in the <nav> tag
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spydaspider/Dickson-Portfolio-Repo/pull/7#discussion_r883322633>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXXCN5IAZN7XFFUFMHCWEJ3VMBVGLANCNFSM5XBFZYGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-27 13:25 UTC, Kossi-stack requested changes
## Hi @spydaspider,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️
- [ ] Kindly add node_modules to .gitignore

 _Check the comments under the review for more changes_.

## Optional suggestions
- [ ] Kindly add a descriptive pull request message, This helps other programmers who want to take a look at your code to understand what changes you made to a particular branch, you can find an example [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects).


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-27 13:35 UTC, spydaspider commented
Will do, thanks!

On Fri, May 27, 2022 at 1:25 PM Kossi Fioklou ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @spydaspider <https://github.com/spydaspider>,
>
> *Good job so far! 👍🏻*
> There are some issues that you still need to work on to go to the next
> project but you are almost there!💪
>
> [image:
> 68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966]
> <https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif>
> To Highlight
>
> ✅ linter error checks validated
> ✅ Documented your work professionally
> ✅ README file is descriptive.
> ✅ Commit messages are meaningful.
> Required Changes ♻️
>
> *Check the comments under the review for more changes*.
> Optional suggestions
>
>    - Kindly add a descriptive pull request message, This helps other
>    programmers who want to take a look at your code to understand what changes
>    you made to a particular branch, you can find an example here
>    <https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects>
>    .
>    - Kindly add node_modules to .gitignore
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spydaspider/Dickson-Portfolio-Repo/pull/7#pullrequestreview-987507461>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXXCN5MZHF5F22677XG6B53VMDENHANCNFSM5XBFZYGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-27 13:51 UTC, spydaspider commented
**Toolbar and Headline of My Portfolio Mobile.**

Added node_modules to the .gitignore file.
Changed my font into a more beautiful one.

2022-05-27 14:13 UTC, KayLemba approved these changes
Hi @spydaspider   ,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

To Highlight 💯
No linters errors ✔️
Descriptive commit messages ✔️

**Optional suggestions**
Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-05-27 14:17 UTC, merged