Added middle section
spydaspider/Dickson-Portfolio-Repo pull request #8
Opened 2022-05-28 11:53 UTC by spydaspider

# Middle Section Of the Mobile Version of my portfolio.
  # The middle section branch contains code for the rest of the portfolio pages which can be found in the images below.
  
- [ ] Bug fix (unexpected generic font-family).
- [ ] New feature ( font-family; Poppins, Arial, Helvetica, sans-serif;)
  - [ ] Run local stylelint config command(npx stylelint "**/*.{css,scss}" --fix  after changing the font.
# Checklist
 [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2022-05-28 13:39 UTC, ShahierNashaat requested changes
Hi @spydaspider , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Please fix your design as there is a space in the right of the design.
![Screenshot from 2022-05-28 15-25-09](https://user-images.githubusercontent.com/33752735/170827929-bbe0affe-6b08-49b8-802a-a1ace0ec5eb9.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 13:39 UTC, ShahierNashaat commented on index.html
> +        <section class = "second-section-wrapper">
- [ ] Kindly be noticed that the container of the works section is a `section` tag.
- [ ] And the main container of the projects has a `display:grid`.

2022-05-28 13:39 UTC, ShahierNashaat commented on index.html
> +        <div class = "grid-section-wrapper">
- [ ] Kindly be noticed that the container of the about me section is a `section` tag.

2022-05-28 13:39 UTC, ShahierNashaat commented on index.html
> +             </div>
- [ ] Kindly be noticed that the technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`.

2022-05-28 14:06 UTC, spydaspider commented on index.html
> +             </div>
Thank you Sir! I will 
attend to the errors at once.

2022-05-30 18:00 UTC, Kossi-stack requested changes
## Hi @,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ Commit messages are meaningful.

## Required Changes ♻️
 - [ ] Please make sure to use [this readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) and please be sure to edit all of the sections to better suit your project.
 - [ ] Kindly remove one Author in the readme since you are alone on this project
 

![Capturer](https://user-images.githubusercontent.com/81444338/171041770-ca1d8819-9666-4321-932c-f40b31f06dfd.PNG)
  
![image](https://user-images.githubusercontent.com/81444338/171041820-b69e1475-b88e-4698-824a-50ab331097ff.png)
 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-30 18:12 UTC, spydaspider commented
Thanks for the feedback!

On Mon, 30 May 2022, 6:00 pm Kossi Fioklou, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @,
>
> *Good job so far! 👍🏻*
> There are some issues that you still need to work on to go to the next
> project but you are almost there!💪
>
> [image:
> 68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966]
> <https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif>
> To Highlight
>
> ✅ Descriptive pull request message
> ✅ linter error checks validated
> ✅ Documented your work professionally
> ✅ Commit messages are meaningful.
> Required Changes ♻️
>
>    - Please make sure to use this readme template
>    <https://github.com/microverseinc/readme-template/blob/master/README.md>
>    and please be sure to edit all of the sections to better suit your project.
>    - Kindly remove one Author in the readme since you are alone on this
>    project
>
> [image: Capturer]
> <https://user-images.githubusercontent.com/81444338/171041770-ca1d8819-9666-4321-932c-f40b31f06dfd.PNG>
>
> [image: image]
> <https://user-images.githubusercontent.com/81444338/171041820-b69e1475-b88e-4698-824a-50ab331097ff.png>
> *Check the comments under the review for more changes*.
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.
> ------------------------------
>
> In index.html
> <https://github.com/spydaspider/Dickson-Portfolio-Repo/pull/8#discussion_r885013330>
> :
>
> >          </div>
>
> -    </div>
>
> +      </section>
>
> +      <section id="section-3" class="contain grid">
>
> +        <div class="s3-container">
>
> +          <div class="image-container3"></div>
>
> +
>
> +          <h1 class = "newh3">Tonic</h1>
>
>
>
>    - Kindly make your design look like Figma design
>    - Your Design
>    [image: Capturetio]
>    <https://user-images.githubusercontent.com/81444338/171040893-d6fdffd9-dc43-4a30-b0cd-4980a5f7d477.PNG>
>    - Figma design
>    [image: Capturefi]
>    <https://user-images.githubusercontent.com/81444338/171040984-18ab25fc-ea38-49e1-ab00-df6bf70dfc99.PNG>
>
> ------------------------------
>
> In index.html
> <https://github.com/spydaspider/Dickson-Portfolio-Repo/pull/8#discussion_r885013375>
> :
>
> > +           <a href = "">Get my resume</a>
>
> +         </div>
>
> +         <div class = "langv">
>
> +           <h3>Languages </h3>
>
> +           <img src = "images/Union.png" alt = "icon">
>
> +         </div>
>
> +         <div class = "tech">
>
> +          <ul>
>
> +            <li class = "item1"><img src = "images/Frame9.png" alt = "image"></li>
>
> +            <li class = "item2"><img src = "images/Frame10.png" alt = "image"></li>
>
> +            <li class = "item3"><img src = "images/Frame11.png" alt = "image"></li>
>
> +          </ul>
>
> +         </div>
>
> +         <div class = "frame">
>
> +          <h3>Frameworks </h3>
>
> +          <img src = "images/Union1.png" alt = "icon">
>
>
>
>    - Kindly Fix the icon
>    [image: Captureico]
>    <https://user-images.githubusercontent.com/81444338/171041208-b8c1f409-27a7-4c7b-bd31-13108dad52bc.PNG>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spydaspider/Dickson-Portfolio-Repo/pull/8#pullrequestreview-989598628>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXXCN5LBPALV2T6Y4TGBAJ3VMT65HANCNFSM5XGRMV4Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-30 21:44 UTC, spydaspider commented
Awesome, thanks!

On Mon, 30 May 2022, 9:39 pm Mihreteab Misganaw, ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> *Hi @spydaspider <https://github.com/spydaspider>,*
> Status: APPROVED 🏆 🎉
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it 🚀:
> Congratulations! 🎉
> To highlight 🎯
>
>    - The Pull Request is following the GitHub Flow ✅
>    - The PR title and description are professional and descriptive ✅
>    - The commit messages are meaningful ✅
>    - The README is well documented ✅
>    - Linters are working properly ✅
>
> [image: Alt Text]
> <https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966>
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spydaspider/Dickson-Portfolio-Repo/pull/8#pullrequestreview-989690763>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXXCN5I37XJZ6TR2N2DN7V3VMUYRDANCNFSM5XGRMV4Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-31 04:39 UTC, merged